/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ccore_jni_SKFJni */

#ifndef _Included_com_ccore_jni_SKFJni
#define _Included_com_ccore_jni_SKFJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_ConnectDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1ConnectDev
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_DisconnectDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1DisconnectDev
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_SetAppPath
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1SetAppPath
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
